# Generated by Django 6.0.7 on 2026-08-06 18:05

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplanetype",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_type_image_path
            ),
        ),
    ]
