# Generated by Django 6.0.7 on 2026-08-07 09:30

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_airplanetype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Representative image of the airplane type.",
                null=True,
                upload_to=airport.models.airplane_type_image_path,
            ),
        ),
    ]
