# Generated by Django 6.0.7 on 2026-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("dispatcher", "Dispatcher"),
                    ("crew", "Crew"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
